/*
 * *
 *  * Created by Vladimir Belov on 27.07.2026, 11:42
 *  * Copyright (c) 2018 - 2026. All rights reserved.
 *  * Last modified 27.07.2026, 07:53
 *
 */

buildscript {

    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        //https://developer.android.com/build/releases/gradle-plugin
        classpath 'com.android.tools.build:gradle:9.4.0-alpha06'
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
    }
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile).tap {
            configureEach {
                options.compilerArgs << "-Xlint:unchecked"
                //options.compilerArgs << "-Xlint:deprecation"
            }
        }
    }
}
