#
# /**
#  * Created by Vladimir Belov on 01.07.2026, 17:28
#  * Copyright (c) 2018 - 2026. All rights reserved.
#  * Last modified 01.07.2026, 13:58
#  */
#

## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

android.debug.obsoleteApi=true
org.gradle.warning.mode=all
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"
android.buildTypes.release.ndk.debugSymbolLevel=FULL
android.useAndroidX=true
org.gradle.configuration-cache=true
android.sync.suppressAgpWarnings=CANNOT_BUILD_SELECTED_TARGET_ABI, UNSUPPORTED_PROJECT_OPTION_USE